"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-08 18:26:08.687549

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_number", sa.String(), nullable=True),
        sa.Column("caller_ani", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content_flagged", sa.Boolean(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_caller_ani"), "threads", ["caller_ani"], unique=False)
    op.create_index(op.f("ix_threads_ref_number"), "threads", ["ref_number"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("fax_id", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_events_event_id"), "webhook_events", ["event_id"], unique=True)
    op.create_index(
        op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_webhook_events_fax_id"), "webhook_events", ["fax_id"], unique=False)
    op.create_table(
        "inbound_faxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fax_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("from_number", sa.String(), nullable=False),
        sa.Column("to_number", sa.String(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("pdf_path", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("inbound_summary", sa.Text(), nullable=True),
        sa.Column("reply_body", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbound_faxes_fax_id"), "inbound_faxes", ["fax_id"], unique=True)
    op.create_index(
        op.f("ix_inbound_faxes_from_number"), "inbound_faxes", ["from_number"], unique=False
    )
    op.create_table(
        "outbound_faxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fax_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("to_number", sa.String(), nullable=False),
        sa.Column("reply_to_fax_id", sa.String(), nullable=True),
        sa.Column("media_url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbound_faxes_fax_id"), "outbound_faxes", ["fax_id"], unique=True)
    op.create_index(
        op.f("ix_outbound_faxes_to_number"), "outbound_faxes", ["to_number"], unique=False
    )
    op.create_table(
        "gallery_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inbound_fax_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("in_pages", sa.Integer(), nullable=False),
        sa.Column("tx_pages", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["inbound_fax_id"],
            ["inbound_faxes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gallery_items_inbound_fax_id"), "gallery_items", ["inbound_fax_id"], unique=True
    )
    op.create_index(op.f("ix_gallery_items_slug"), "gallery_items", ["slug"], unique=True)
    op.create_index(op.f("ix_gallery_items_status"), "gallery_items", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gallery_items_status"), table_name="gallery_items")
    op.drop_index(op.f("ix_gallery_items_slug"), table_name="gallery_items")
    op.drop_index(op.f("ix_gallery_items_inbound_fax_id"), table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_index(op.f("ix_outbound_faxes_to_number"), table_name="outbound_faxes")
    op.drop_index(op.f("ix_outbound_faxes_fax_id"), table_name="outbound_faxes")
    op.drop_table("outbound_faxes")
    op.drop_index(op.f("ix_inbound_faxes_from_number"), table_name="inbound_faxes")
    op.drop_index(op.f("ix_inbound_faxes_fax_id"), table_name="inbound_faxes")
    op.drop_table("inbound_faxes")
    op.drop_index(op.f("ix_webhook_events_fax_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_threads_ref_number"), table_name="threads")
    op.drop_index(op.f("ix_threads_caller_ani"), table_name="threads")
    op.drop_table("threads")
    # ### end Alembic commands ###
