"""reliability and privacy columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-08 23:44:02.838272

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("outbound_id", sa.Integer(), nullable=False),
        sa.Column("telnyx_fax_id", sa.String(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["outbound_id"],
            ["outbound_faxes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_attempts_outbound_id"), "outbound_attempts", ["outbound_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbound_attempts_telnyx_fax_id"),
        "outbound_attempts",
        ["telnyx_fax_id"],
        unique=True,
    )
    # server_default so the NOT NULL add works on a populated production table;
    # historical rows genuinely had zero processing attempts under this scheme.
    op.add_column(
        "inbound_faxes", sa.Column("attempts", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "inbound_faxes", sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("outbound_faxes", "fax_id", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "threads", sa.Column("removal_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "removal_requested_at")
    op.alter_column("outbound_faxes", "fax_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("inbound_faxes", "claimed_at")
    op.drop_column("inbound_faxes", "attempts")
    op.drop_index(op.f("ix_outbound_attempts_telnyx_fax_id"), table_name="outbound_attempts")
    op.drop_index(op.f("ix_outbound_attempts_outbound_id"), table_name="outbound_attempts")
    op.drop_table("outbound_attempts")
    # ### end Alembic commands ###
